# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core', '~> 5.15.0'
pod 'Firebase/Messaging', '~> 5.15.0'
pod 'Fabric', '~> 1.7.13'
pod 'Crashlytics', '~> 3.10.7'

target 'tillionREACTNATIVE' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!


  # Pods for tillionREACTNATIVE

end
